// See https://aka.ms/new-console-template for more information


using System;

string forename = String.Empty;
string surname = String.Empty;
string middlename = String.Empty;
string gender = String.Empty;
DateTime dateOfBirth = DateTime.Now;
Random random = new Random();

void SetForname()
{
    Console.WriteLine("Please insert your Forename");
    forename = Console.ReadLine();
}
void SetMiddlename()
{
    Console.WriteLine("Please insert your MiddleName (just hit enter for none)");
    middlename = Console.ReadLine();    
}
void SetSurname()
{
    Console.WriteLine("Please insert your Surname");
    surname = Console.ReadLine();
}
void SetDOB()
{
    bool validDOB = false;
    while (!validDOB)
    {
        Console.WriteLine("Please insert your Date Of Birth");
        var dob = Console.ReadLine();
        validDOB = DateTime.TryParse(dob, out dateOfBirth);
    }
}
void SetGender()
{
    bool validGender = false;
    while (!validGender)
    {
        Console.WriteLine("Please set your gender (m or f)");
        var input = Console.ReadLine();
        gender = input is not null ? input.ToLower() : String.Empty;
        switch(gender)
        {
            case "m": 
            case "f": 
                validGender = true;
                break;
        }
        
    }
}

string RandomString(int length)
{
    const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    return new string(Enumerable.Repeat(chars, length)
      .Select(s => s[random.Next(s.Length)]).ToArray());
}

void BuildDrivingLicenseNumber()
{
    var DLNumber = string.Empty;
    surname = surname.PadRight(5, '9');

    string part1 = surname.Substring(0, 5);
    string part2 = dateOfBirth.ToString("yy").Substring(0, 1);
    string part3 = dateOfBirth.ToString("MM");
    if (gender == "f")
    {
        int month = (int.Parse(part3) + 5) % 12;
        part3 = month.ToString().PadLeft(2, '0');
    }
    string part4 = dateOfBirth.ToString("dd");
    string part5 = dateOfBirth.ToString("yy").Substring(1, 1);
    if (middlename.Trim() == "")
    {
        middlename = "9";
    }
    string part6 = forename.Substring(0, 1) + middlename.Substring(0, 1);
    string part7 = "9";
    string part8 = RandomString(2);
    string divingLicense = (part1 + part2 + part3 + part4 + part5 + part6 + part7 + part8).ToUpper();
    Console.WriteLine("Here is a autogenerated Driving license");
    Console.WriteLine(divingLicense);

}

SetForname();
SetMiddlename();
SetSurname();
SetDOB();
SetGender();
BuildDrivingLicenseNumber();